---
title: Hanuman
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Hanuman is a minimal yet powerful Jekyll theme for your blogs and websites.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/hanuman/"
url: https://samanyougarg.com
paginate: 5
facebook: facebook
twitter: twitter
github: github
about: about
contact: contact
privacy-policy: privacy-policy
permalink: "/:title"
analytics_id: ''
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
- jekyll-paginate
safe: false
lsi: false
username: samanyougarg
repo: hanuman
branch: master
relative_source: "../hanuman/"
destination: "../hanuman-pages/"
production_url: https://samanyougarg.com/
source_url: https://github.com/samanyougarg/hanuman
exclude:
- README.md
- Rakefile
- Gemfile
- Gemfile.lock
- changelog.md
- "*.Rmd"
- vendor
- ".travis.yml"
